apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
#  namespace: logging
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      format json
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type parser
      key_name log
      format json
    </filter>

    <match **>
      @type elasticsearch
      @id out_es
      host elasticsearch.default.svc.cluster.local
      port 9200
      scheme http
      logstash_format true
      logstash_prefix fluentd
      <buffer>
      flush_intervals 10s
      </buffer>
      include_tag_key true
      type_name _doc
    </match>


