apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
#  namespace: logging
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.pos
      tag kubernetes.*
      format json
    </source>

    <filter kubernetes.**>
      @type parser
      key_name log
      format json
    </filter>

    <match **>
      @type elasticsearch
      @id out_es
      host elasticsearch.default.svc.cluster.local
      port 9200
      scheme http
      logstash_format true
      logstash_prefix kubernetes-logs
      include_tag_key true
      type_name _doc
    </match>


